log:
  level: info

inbounds:
  - type: vless
    tag: vless-in
    listen: "0.0.0.0"
    listen_port: 8080
    users:
      - uuid: "9fb01a22-33f1-4e9e-b5a5-e18fde50707a"
    transport:
      type: ws
      path: "/vless-cdn"

outbounds:
  - type: freedom
    tag: direct
